### PR TITLE
Add support for Streaming API

### LINKED ISSUE #11: Streaming support
Is streaming support planned, or was it left out due to technical limitations?

### PR DESCRIPTION
**Pull request by AlgorithmsAreCool**
This should be in pretty decent shape. I've added some more basic tests that validate round tripping. 

I've also validated this on a ~50MB log file at various a couple of compression levels. 

Some rough testing indicates ~550MB/s Compression and ~875MB/s at level 1.

Let me know what you think.

fixes #11

### CODE REVIEW

**Comment by AlgorithmsAreCool** [comment]
Also included in this is a change to remove allocations from non-streaming compression and decompression.

Here are some timing figures from before and after commit 22056f7

**Before Changes**

|              Method |        Mean |     Error |    StdDev |  Gen 0 | Allocated |
|-------------------- |------------:|----------:|----------:|-------:|----------:|
|   Compress1KBRandom | 14,023.5 ns | 73.360 ns | 68.621 ns | 0.0153 |      80 B |
| Decompress1KBRandom |    254.0 ns |  5.116 ns |  6.652 ns | 0.0186 |      80 B |

**After Changes**

|              Method |        Mean |      Error |     StdDev | Allocated |
|-------------------- |------------:|-----------:|-----------:|----------:|
|   Compress1KBRandom | 13,982.4 ns | 32.6861 ns | 30.5745 ns |       0 B |
| Decompress1KBRandom |    232.1 ns |  0.9317 ns |  0.7780 ns |       0 B |

**Comment by Grantelbob** [comment]
push

**Comment by AlgorithmsAreCool** [comment]
@Grantelbob  I don't think this repo is active anymore :/

**Comment by Grantelbob** [comment]
yeah, seems like that... Sad :/

As a workaround i downloaded and build your streaming fork manually (https://github.com/AlgorithmsAreCool/ZstdNet/tree/Streaming), right after swapping out Zstd DLL for newest version. Works great until now (+ using Dict) :)

Thank you very much for your efford!

**Comment by AlgorithmsAreCool** [comment]
I'm very glad to hear it works for you. Maybe I should try to fork it permanently

**Comment by AlgorithmsAreCool** [comment]
Whoa!

**Pull request merged**
